# Generated by Django 6.0.6 on 2026-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_posts/"),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=120)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
