# Generated by Django 6.0.6 on 2026-06-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "images_note",
                    models.CharField(
                        blank=True,
                        help_text="Images are uploaded separately below this project.",
                        max_length=255,
                    ),
                ),
                ("live_website_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "custom_tech_stack",
                    models.TextField(
                        blank=True,
                        help_text="Write extra tools, languages, frameworks or methods not listed above.",
                    ),
                ),
                (
                    "deployment",
                    models.CharField(
                        blank=True,
                        help_text="Example: Heroku, Vercel, Netlify, Render, Railway, PythonAnywhere.",
                        max_length=180,
                    ),
                ),
                (
                    "databases",
                    models.CharField(
                        blank=True,
                        help_text="Example: PostgreSQL, SQLite, MySQL, MongoDB.",
                        max_length=220,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tech stack",
                "verbose_name_plural": "Tech stack",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio_projects/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("github_url", models.URLField(blank=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Example: Frontend developer, Backend developer, Designer.",
                        max_length=120,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="tech_stack",
            field=models.ManyToManyField(
                blank=True, related_name="portfolio_projects", to="portfolio.techstack"
            ),
        ),
    ]
