# Generated by Django 6.0.6 on 2026-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_seed_tech_stack_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("hackathon", "Hackathon Project"),
                    ("portfolio", "Portfolio Project"),
                    ("freelance", "Freelance Project"),
                ],
                default="portfolio",
                max_length=20,
            ),
        ),
    ]
