# Generated by Django 6.0.6 on 2026-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_portfolioproject_project_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioproject",
            options={"ordering": ["display_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="display_order",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Lower numbers appear first. Example: 1 is shown before 2.",
            ),
        ),
    ]
