# Generated by Django 6.0.6 on 2026-06-26 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional short preview text shown on the CV page.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="cv_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers appear first. Example: 1 is shown before 2.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
