# Generated by Django 6.0.6 on 2026-07-12 14:10

import config.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvdocument",
            name="file",
            field=models.FileField(
                storage=config.storage_backends.get_raw_media_storage,
                upload_to="cv_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
