# Generated by Django 6.0.6 on 2026-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=180)),
                ("message", models.TextField()),
                ("email_sent", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Do you want to build something?", max_length=180
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        blank=True, default="I can help you with that.", max_length=220
                    ),
                ),
                ("intro_text", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=60)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Use international format, for example +46701234567.",
                        max_length=60,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=220)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username, @username, phone number or full URL.",
                        max_length=180,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact profile",
                "verbose_name_plural": "Contact profile",
            },
        ),
    ]
