# Generated by Django 6.0.6 on 2026-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="error_message",
        ),
    ]
