# Generated by Django 6.0.6 on 2026-07-10 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("institution", models.CharField(blank=True, max_length=180)),
                (
                    "education_type",
                    models.CharField(
                        choices=[
                            ("formal", "Formal education"),
                            ("higher_education", "Higher education"),
                            ("vocational", "Vocational education"),
                            ("bootcamp", "Bootcamp"),
                            ("course", "Course"),
                            ("certification", "Certification"),
                            ("self_study", "Self study"),
                            ("school", "School"),
                            ("other", "Other"),
                        ],
                        default="formal",
                        max_length=40,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="education/images/"
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                (
                    "link_text",
                    models.CharField(blank=True, default="View more", max_length=80),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Example: fa-solid fa-graduation-cap, fa-solid fa-brain, fa-solid fa-certificate",
                        max_length=120,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#f97316",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #f97316.",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-start_date", "title"],
            },
        ),
    ]
