# Generated by Django 6.0.6 on 2026-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(default="Current focus", max_length=80),
                ),
                (
                    "badge_color",
                    models.CharField(
                        choices=[
                            ("primary", "Blue / Primary"),
                            ("secondary", "Gray / Secondary"),
                            ("success", "Green / Success"),
                            ("danger", "Red / Danger"),
                            ("warning", "Yellow / Warning"),
                            ("info", "Cyan / Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("hero_title", models.CharField(max_length=220)),
                ("hero_text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home/hero/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home hero",
                "verbose_name_plural": "Home hero",
            },
        ),
    ]
