# Generated by Django 6.0.6 on 2026-06-30 13:05

import django.core.validators
import django.db.models.deletion
import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("issuer", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("award_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resume/awards/",
                        validators=[resume.models.validate_award_file],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-award_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResumeIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Resume", max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resume intro",
                "verbose_name_plural": "Resume intro",
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "color_hex",
                    models.CharField(
                        default="#0dcaf0",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #0dcaf0.",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#0dcaf0",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #0dcaf0.",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Example: fa-brands fa-html5 or fa-brands fa-python",
                        max_length=120,
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="resume/skill-meter-icons/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("organization", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("education", "Education"),
                            ("military", "Military service"),
                            ("psychology", "Psychology"),
                            ("data_science", "Data Science"),
                            ("other", "Other"),
                        ],
                        default="work",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Example: fa-brands fa-react or fa-solid fa-brain",
                        max_length=120,
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="resume/skill-icons/"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#0dcaf0",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #0dcaf0.",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resume.skillgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group__display_order", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperienceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=280)),
                ("display_order", models.PositiveIntegerField(default=100)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="resume.workexperience",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
