# Generated by Django 6.0.6 on 2026-07-02 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_seed_resume_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="color_hex",
            field=models.CharField(
                default="#a3ff94",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, for example #0dcaf0.",
                        regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Example: fa-solid fa-briefcase, fa-solid fa-graduation-cap, fa-solid fa-shield-halved",
                max_length=120,
            ),
        ),
    ]
