# Generated by Django 6.0.6 on 2026-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_workexperience_color_hex_workexperience_icon_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillgroup",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Example: fa-solid fa-code, fa-solid fa-database, fa-solid fa-brain",
                max_length=120,
            ),
        ),
    ]
