# Generated by Django 6.0.6 on 2026-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_skillgroup_icon_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeintro",
            name="title",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
