# Generated by Django 6.0.6 on 2026-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_alter_resumeintro_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillgroup",
            name="show_in_profile",
            field=models.BooleanField(
                default=False,
                help_text="Show this group as a large card in the Technical profile / My Skills section.",
            ),
        ),
    ]
