# Generated by Django 6.0.6 on 2026-07-12 14:10

import config.storage_backends
import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_skillgroup_show_in_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=config.storage_backends.get_raw_media_storage,
                upload_to="resume/awards/",
                validators=[resume.models.validate_award_file],
            ),
        ),
    ]
